services:
  postgres:
    image: postgres:15
    container_name: yummi-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - yummi

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yummi-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      USDA_API_KEY: ${USDA_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    command: >
      sh -c "npx prisma db push && npm run dev"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'node -e "require(''http'').get(''http://localhost:3000/health'', r=>process.exit(r.statusCode===200?0:1)).on(''error'',()=>process.exit(1))"',
        ]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - yummi

networks:
  yummi:
    driver: bridge

volumes:
  postgres_data:
