detection_model:
  name: "yolov8s"
  pretrained: True
  classes: 18

freshness_model:
  type: "timm"
  name: "efficientnet_b2"
  pretrained: True
  classes: 3
  input_size: 224

training:
  detection:
    epochs: 300
    batch_size: 32
    img_size: 640
    patience: 50

  freshness:
    epochs: 100
    batch_size: 64
    img_size: 224
    patience: 20

  device: "auto"
  workers: 8
  seed: 42
  folds: 5

# Data Paths
data:
  detection_data: "data_detection.yaml"
  freshness_data: "datasets/freshness/"

# Optimizer
optimizer:
  detection:
    name: "AdamW"
    lr0: 0.01
    weight_decay: 0.0005

  freshness:
    name: "AdamW"
    lr0: 0.001
    weight_decay: 0.0001

# Augmentation
augmentation:
  detection:
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 15.0
    fliplr: 0.5
    mosaic: 1.0

    # turn on if have few data
    mixup: 0.1
    copy_paste: 0.1

  freshness:
    rotation: 15
    brightness: 0.2
    contrast: 0.2
    saturation: 0.15 # important for freshness
    hue: 0.03
    horizontal_flip: 0.5
    vertical_flip: 0.1
    blur_prob: 0.12
    noise_prob: 0.10
    shadow_prob: 0.10
    coarse_dropout_prob: 0.05

# Inference
inference:
  detection_confi: 0.4
  detection_iou: 0.5
  freshness_confi: 0.8
  crop_margin: 0.08 # expand crop box by 8%
  tta: true
  ensemble_folds: true
